version: "3.8"

services:
  poetry:
    platform: linux/x86_64
    image: localhost/de-zoomcamp:build
    entrypoint: poetry
    build:
      dockerfile: Dockerfile
      target: build
      context: .
      args:
        POETRY_OPTIONS: "--no-root --with=dev"
    profiles:
      - cli
    volumes:
      - type: bind
        source: .
        target: /pyproject
      - type: volume
        source: pip-cache
        target: /var/cache/pip
      - type: volume
        source: poetry-cache
        target: /var/cache/pypoetry

  dev: &python-development
    platform: linux/x86_64
    image: localhost/de-zoomcamp:dev
    command: exit 0
    build:
      dockerfile: Dockerfile
      target: runtime
      context: .
      args:
        POETRY_OPTIONS: "--no-root --with=dev"
    volumes:
      - type: bind
        source: .
        target: /home/zoomcamp/de_zoomcamp
    environment:
      - PYTHONDONTWRITEBYTECODE=true
    env_file:
      - .env

  jupyter:
    <<: *python-development
    ports:
      - "8888"
    profiles:
      - dev
    command:
      - jupyter
      - notebook
      - --no-browser
      - --ip=0.0.0.0
      - --NotebookApp.iopub_data_rate_limit=100000000
      - --NotebookApp.token="$JUPYTER_TOKEN"

  pgdatabase:
    image: postgres:13
    ports:
      - "5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pip-cache:
    external: true

  poetry-cache:
    external: true

  pgdata:
    driver: local
